"""empty message

Revision ID: e9e9ee468924
Revises: 42a0071b08a6
Create Date: 2019-03-29 15:03:20.621692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e9ee468924'
down_revision = '42a0071b08a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('wait_time_stddev', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction', 'wait_time_stddev')
    # ### end Alembic commands ###
